### ISSUE TITLE
Error de tipeo en malla MAT

### ISSUE THREAD

**Issue by cristobal-montecino** [BooterMan98/malla-interactiva#32]
En la [Malla Interactiva Ing. Civil Matemática](https://mallas.labcomp.cl/?m=MAT), 

![tipeo](https://user-images.githubusercontent.com/45719570/182004264-cbf8dddd-5220-43cb-9172-8e0ec41b904e.png)

Dice `ingenería` cuando debe decir `ingeniería`. Según la [RAE](https://www.rae.es), [ingenería no existe](https://dle.rae.es/Ingener%C3%ADa?m=form).

**Comment by BooterMan98** [comment]
Hola, gracias por tu pequeño aporte! Dentro de poco se verá reflejado en mallas.labcomp.cl :P
