### ISSUE TITLE
Generadora se estanca al generar una malla nueva

### ISSUE THREAD

**Issue by maripidays** [BooterMan98/malla-interactiva#34]
Medicina Veterinaria Uchile

MEDVET
Agregue todos los ramos de mi malla, y tambien le puse las categorias, ahora cuando la genero, solo aparece el primer semestre y no se bien como hacerlo jiji, por si puedes helpearme, garcias :D

<details>
<summary> <strong>Información de la malla (Fotos) </strong> </summary>

![image](https://user-images.githubusercontent.com/86386022/182286533-fdbf421d-b39b-4274-afb8-1442b0237e8e.png)
![image](https://user-images.githubusercontent.com/86386022/182286755-6877f116-2485-4219-8b59-22209fad0ace.png)
![image](https://user-images.githubusercontent.com/86386022/182286786-48867495-3fad-45cf-bf34-76f8b2dcacf6.png)
![image](https://user-images.githubusercontent.com/86386022/182286836-e2202e2d-4a03-4997-999e-1c19f7e3cea7.png)
![image](https://user-images.githubusercontent.com/86386022/182287063-038048c5-13a8-41f5-86a8-bc63ee42db94.png)
</details>

**Comment by BooterMan98** [comment]
Voy a necesitar un poco más de info, específicamente los ramos del semestre n°3 y del último ramo que aparece en la malla generada del segundo semestre.

Adjunta la misma foto que subiste pero mostrando el semestre 3
>  ![image](https://user-images.githubusercontent.com/86386022/182286836-e2202e2d-4a03-4997-999e-1c19f7e3cea7.png) 

y adjunta esta foto pero mostrando el ramo que se encuentran más abajo
> ![image](https://user-images.githubusercontent.com/86386022/182287063-038048c5-13a8-41f5-86a8-bc63ee42db94.png)

**Comment by maripidays** [comment]
Semestre 3
![image](https://user-images.githubusercontent.com/86386022/182401339-5a1b2071-2f65-4f37-988e-873543722ab4.png)

Malla generada
![image](https://user-images.githubusercontent.com/86386022/182401515-7cfd9262-7bfa-455b-8a7a-bba492979644.png)

**Comment by BooterMan98** [comment]
Ya, el problema parece estar en el ramo "Electivo" o en "Desarrollo del organismo animal", revisa en "*Editar*" que tengan una categoría asignada, no tengan prerrequisitos (por como) y los créditos estén bien (que estén en 0 en "Electivo" no debería ser un problema).


Si aún no se puede ver la malla voy a necesitar lo siguiente: 
1. En la pagina generadora, presiona F12 para abrir las herramientas de desarrollador
2.
    <details>
    <summary> Dirigete a la pestana de *Aplicación*</summary>
    
   ![Captura de pantalla 2022-08-02 115747](https://user-images.githubusercontent.com/20160120/182421772-4bc4e8d4-b0d7-4aa8-a5af-8c0e08fa3c3b.png)

    </details>
3. En la sección de *Almacenamiento*, abre el contenido de *Almacenamiento local* y selecciona la página de la malla
4.
    <details>
    <summary>Copia todo el contenido de <code>generatorUserCategoryINF</code>, <code>generatorUserSubjectsINF</code> y <code>generatorUserDataINF</code> y lo pegas en la próxima respuesta</summary>

    ![Captura de pantalla 2022-08-02 120411](https://user-images.githubusercontent.com/20160120/182422651-b01dba60-b4fa-458e-90c0-e713cf70e14e.png)

    </details>

**Comment by maripidays** [comment]
aparecio parte del tercer semestre pero ahi quedo
![image](https://user-images.githubusercontent.com/86386022/182440292-02da0a26-0458-4316-a074-91110eab627f.png)
**no se si era esto lo que necesitabas jeje, disculpa si no, apenas se sacar pantallazos en el pc xddd**

{Custom: ["#000000", "Fuera de la malla | editado"], CB: ["#70a0ff", "Ciclo basico"],…}
CB: ["#70a0ff", "Ciclo basico"]
0: "#70a0ff"
1: "Ciclo basico"
CP: ["#12f34a", "Ciclo Profesional"]
0: "#12f34a"
1: "Ciclo Profesional"
CPP: ["#4034e5", "Ciclo Pre-Profesional"]
0: "#4034e5"
1: "Ciclo Pre-Profesional"
Custom: ["#000000", "Fuera de la malla | editado"]
0: "#000000"
1: "Fuera de la malla | editado"

{AU1: ["Bases Moleculares", "10", "CB", [], 0, ""], CU7: ["Diversidad animal", "7", "CB", [], 0, ""],…}
"": ["INTERNADO", "", "CP", [], 0, ""]
0: "INTERNADO"
1: ""
2: "CP"
3: []
4: 0
5: ""
AU1: ["Bases Moleculares", "10", "CB", [], 0, ""]
0: "Bases Moleculares"
1: "10"
2: "CB"
3: []
4: 0
5: ""
AU2: ["Bases Moleculares y celulares", "10", "CB", ["AU1"], 0, ""]
0: "Bases Moleculares y celulares"
1: "10"
2: "CB"
3: ["AU1"]
0: "AU1"
4: 0
5: ""
AU3: ["Bases celulares", "10", "CB", [], 0, ""]
0: "Bases celulares"
1: "10"
2: "CB"
3: []
4: 0
5: ""
BU4: ["Desarrollo del organismo animal", "14", "CB", [], 0, "A"]
0: "Desarrollo del organismo animal"
1: "14"
2: "CB"
3: []
4: 0
5: "A"
BU5: ["Estructura del organismo animal", "14", "CB", [], 0, "A"]
0: "Estructura del organismo animal"
1: "14"
2: "CB"
3: []
4: 0
5: "A"
BU6: ["Bases inmunologicas", "5", "CB", [], 0, ""]
0: "Bases inmunologicas"
1: "5"
2: "CB"
3: []
4: 0
5: ""
CU7: ["Diversidad animal", "7", "CB", [], 0, ""]
0: "Diversidad animal"
1: "7"
2: "CB"
3: []
4: 0
5: ""
CU8: ["Ecologia", "4", "CB", [], 0, ""]
0: "Ecologia"
1: "4"
2: "CB"
3: []
4: 0
5: ""
CU9: ["Conducta animal", "4", "CB", [], 0, ""]
0: "Conducta animal"
1: "4"
2: "CB"
3: []
4: 0
5: ""
DEW-100: ["Educación Física I", 1, "Custom", [], 2, "A"]
0: "Educación Física I"
1: 1
2: "Custom"
3: []
4: 2
5: "A"
DEW-101: ["Educación Física II", 1, "Custom", ["DEW-100"], 2, "A"]
0: "Educación Física II"
1: 1
2: "Custom"
3: ["DEW-100"]
4: 2
5: "A"
DU10: ["Métodos de cuantificación", 7, "Custom", [], 0, ""]
0: "Métodos de cuantificación"
1: 7
2: "Custom"
3: []
4: 0
5: ""
DU11: ["Bioestadistica", "9", "CB", [], 0, ""]
0: "Bioestadistica"
1: "9"
2: "CB"
3: []
4: 0
5: ""
DU12: ["Epidemiologia", "4", "CB", [], 0, ""]
0: "Epidemiologia"
1: "4"
2: "CB"
3: []
4: 0
5: ""
E: ["Electivo libre", 0, "Custom", [], 0, ""]
ELEC: ["Electivo III", 0, "Custom", [], 0, ""]
EU13: ["Fisiologia I", "7", "CB", [], 0, ""]
EU14: ["Fisiologia II", "9", "CB", [], 0, ""]
EU15: ["Farmacología general", "4", "CB", [], 0, ""]
Elec: ["electivo IV", "0", "CPP", [], 0, ""]
FIS-100: ["Introducción a la Física", 3, "Custom", [], 6, "A"]
FIS-110: ["Física General I", 5, "Custom", ["MAT-021", "FIS-100"], 8, "A"]
FIS-120: ["Física General II", 4, "Custom", ["MAT-022", "FIS-110"], 8, "A"]
FIS-130: ["Física General III", 4, "Custom", ["MAT-022", "FIS-110"], 8, "A"]
FIS-140: ["Física General IV", 4, "Custom", ["FIS-130", "FIS-120"], 8, "A"]
FU16: ["Agentes biológicos patógenos", "7", "CPP", [], 0, ""]
0: "Agentes biológicos patógenos"
1: "7"
2: "CPP"
3: []
4: 0
5: ""
FU17: ["Enfermedades infecciosas y parasitarias", "14", "CPP", [], 0, ""]
0: "Enfermedades infecciosas y parasitarias"
1: "14"
2: "CPP"
3: []
4: 0
5: ""
GU18-19: ["Bases economicas y administrativas", "10", "", [], 0, "A"]
0: "Bases economicas y administrativas"
1: "10"
2: ""
3: []
4: 0
5: "A"
HRW-132: ["Humanístico I", 2, "Custom", [], 3, "A"]
HRW-133: ["Humanístico II", 2, "Custom", [], 3, "A"]
HU20: ["Patologia I", "13", "CPP", [], 0, ""]
0: "Patologia I"
1: "13"
2: "CPP"
3: []
4: 0
5: ""
HU21: ["Patologia II", "13", "CPP", ["MICB", "EU14", "EU15", "BU6"], 0, ""]
0: "Patologia II"
1: "13"
2: "CPP"
3: ["MICB", "EU14", "EU15", "BU6"]
0: "MICB"
1: "EU14"
2: "EU15"
3: "BU6"
4: 0
5: ""
HU22: ["Patología III", "3", "CPP", [], 0, ""]
0: "Patología III"
1: "3"
2: "CPP"
3: []
4: 0
5: ""
HU23: ["Patología diagnostica", "6", "CPP", [], 0, ""]
0: "Patología diagnostica"
1: "6"
2: "CPP"
3: []
4: 0
5: ""
ICN-270: ["Información y Matemáticas Financieras", 3, "Custom", ["IWN-170"], 5, "I"]
INF-1: ["Libre I", 1, "Custom", [], 2, "A"]
INF-2: ["Libre II", 1, "Custom", [], 2, "A"]
INF-3: ["Libre III", 1, "Custom", [], 2, "A"]
INF-4: ["Libre IV", 1, "Custom", [], 2, "A"]
INF-5: ["Libre V", 1, "Custom", [], 2, "A"]
INF-6: ["Libre VI", 1, "Custom", [], 2, "A"]
INF-7: ["Libre VII", 1, "Custom", [], 2, "A"]
INF-134: ["Estructuras de Datos", 3, "Custom", ["IWI-131"], 5, "A"]
INF-152: ["Estructuras Discretas", 3, "Custom", ["IWI-131", "MAT-021"], 5, "A"]
INF-155: ["Informática Teórica", 3, "Custom", ["INF-134", "INF-152"], 5, "A"]
INF-221: ["Algoritmos y Complejidad", 3, "Custom", ["INF-152", "INF-253"], 5, "A"]
INF-225: ["Ingeniería de Software", 3, "Custom", ["INF-236"], 5, "I"]
INF-228: ["Taller Desarrollo de Proyecto de Informática", 6, "Custom", ["INF-360"], 10, "P"]
INF-236: ["Análisis y Diseño de Software", 3, "Custom", ["INF-239", "INF-253"], 5, "A"]
INF-239: ["Bases de Datos", 3, "Custom", ["INF-134"], 5, "A"]
INF-245: ["Arquitectura y Organización de Computadores", 3, "Custom", ["INF-134"], 5, "A"]
INF-246: ["Sistemas Operativos", 3, "Custom", ["INF-245"], 5, "A"]
INF-253: ["Lenguajes de Programación", 3, "Custom", ["INF-134"], 5, "A"]
INF-256: ["Redes de Computadores", 3, "Custom", ["INF-246"], 5, "I"]
INF-260: ["Teoría de Sistemas", 3, "Custom", ["IWG-101"], 5, "A"]
INF-266: ["Sistemas de Gestión", 3, "Custom", ["INF-276"], 5, "P"]
INF-270: ["Organizaciones y Sistemas de Información", 3, "Custom", ["INF-260"], 5, "A"]
INF-276: ["Ingeniería, Informática y Sociedad", 3, "Custom", ["INF-270"], 5, "A"]
INF-280: ["Estadística Computacional", 3, "Custom", ["IWI-131", "MAT-023"], 5, "A"]
INF-285: ["Computación Científica", 3, "Custom", ["MAT-024", "INF-221"], 5, "I"]
INF-292: ["Optimización", 3, "Custom", ["MAT-023"], 5, "A"]
INF-293: ["Investigación de Operaciones", 3, "Custom", ["INF-280", "INF-292"], 6, "I"]
INF-295: ["Inteligencia Artificial", 3, "Custom", ["INF-292", "INF-221"], 5, "P"]
INF-305: ["Electivo Informática I", 3, "Custom", [], 5, "P"]
INF-306: ["Electivo Informática II", 3, "Custom", [], 5, "A"]
INF-307: ["Electivo Informática III", 3, "Custom", [], 5, "A"]
INF-308: ["Electivo Informática IV", 3, "Custom", [], 5, "A"]
INF-309: ["Trabajo de Título 1", 1, "Custom", ["INF-360"], 2, "P"]
INF-310: ["Trabajo de Título 2", 12, "Custom", ["INF-228", "INF-309"], 20, "I"]
INF-311: ["Electivo I", 3, "Custom", [], 5, "A"]
INF-312: ["Electivo II", 3, "Custom", [], 5, "A"]
INF-313: ["Electivo III", 3, "Custom", [], 5, "A"]
INF-314: ["Electivo IV", 3, "Custom", [], 5, "A"]
INF-322: ["Diseño Interfaces Usuarias", 3, "Custom", ["INF-225"], 5, "P"]
INF-343: ["Sistemas Distribuidos", 3, "Custom", ["INF-256"], 5, "P"]
INF-360: ["Gestión de Proyectos de Informática", 3, "Custom", ["INF-322", "INF-266"], 5, "I"]
INGB: ["Ingles beginner", "6", "CB", [], 0, ""]
0: "Ingles beginner"
1: "6"
2: "CB"
3: []
4: 0
5: ""
INGP: ["Ingles Pre-intermedio", "4", "CB", [], 0, "A"]
0: "Ingles Pre-intermedio"
1: "4"
2: "CB"
3: []
4: 0
5: "A"
IU24: ["Introducción a la producción animal", "9", "CPP", [], 0, ""]
0: "Introducción a la producción animal"
1: "9"
2: "CPP"
3: []
4: 0
5: ""
IU25: ["Genetica Basica", "5", "CPP", ["MICB", "EU14", "EU15", "BU6"], 0, ""]
0: "Genetica Basica"
1: "5"
2: "CPP"
3: ["MICB", "EU14", "EU15", "BU6"]
0: "MICB"
1: "EU14"
2: "EU15"
3: "BU6"
4: 0
5: ""
IU27: ["Alimentacion", "5", "CPP", ["MICB", "EU14", "EU15", "BU6"], 0, ""]
0: "Alimentacion"
1: "5"
2: "CPP"
3: ["MICB", "EU14", "EU15", "BU6"]
0: "MICB"
1: "EU14"
2: "EU15"
3: "BU6"
4: 0
5: ""
IWG-101: ["Introducción a la Ingeniería", 2, "Custom", [], 3, "A"]
IWI-131: ["Programación", 3, "Custom", [], 5, "A"]
IWN-170: ["Economía IA", 3, "Custom", ["MAT-023"], 5, "A"]
JU30: ["Bases de tecnologías diagnosticas", "7", "CPP", [], 0, ""]
0: "Bases de tecnologías diagnosticas"
1: "7"
2: "CPP"
3: []
4: 0
5: ""
JU31: ["Métodos de exploración clinica", "9", "CPP", ["MICB", "EU14", "EU15", "BU6"], 0, ""]
0: "Métodos de exploración clinica"
1: "9"
2: "CPP"
3: ["MICB", "EU14", "EU15", "BU6"]
0: "MICB"
1: "EU14"
2: "EU15"
3: "BU6"
4: 0
5: ""
KU32: ["Salud publica veterinaria", "5", "CP", [], 0, ""]
0: "Salud publica veterinaria"
1: "5"
2: "CP"
3: []
4: 0
5: ""
KU33: ["Gestión Ambiental", "4", "CP", [], 0, ""]
0: "Gestión Ambiental"
1: "4"
2: "CP"
3: []
4: 0
5: ""
KU34: ["Inocuidad de los alimentos", "4", "CP", [], 0, ""]
0: "Inocuidad de los alimentos"
1: "4"
2: "CP"
3: []
4: 0
5: ""
KU35: ["Control y aseguramiento de la calidad de los alimentos", "8", "CP",…]
0: "Control y aseguramiento de la calidad de los alimentos"
1: "8"
2: "CP"
3: ["KU34", "MICP", "MACA", "HU22", "UI29", "UI28", "HU23"]
0: "KU34"
1: "MICP"
2: "MACA"
3: "HU22"
4: "UI29"
5: "UI28"
6: "HU23"
4: 0
5: ""
LU35_II: ["Manejo Productivo", "11", "CP", [], 0, ""]
0: "Manejo Productivo"
1: "11"
2: "CP"
3: []
4: 0
5: ""
LU36_I: ["Manjeo productivo", "11", "CP", [], 0, ""]
0: "Manjeo productivo"
1: "11"
2: "CP"
3: []
4: 0
5: ""
LU37: ["Impacto ambiental", "2", "CP", ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"], 0, ""]
0: "Impacto ambiental"
1: "2"
2: "CP"
3: ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"]
0: "MICP"
1: "MACA"
2: "HU22"
3: "UI29"
4: "UI28"
5: "HU23"
4: 0
5: ""
LU43: ["Obstetricia ginecología y manejo reproductivo", "7", "CP", [], 0, ""]
0: "Obstetricia ginecología y manejo reproductivo"
1: "7"
2: "CP"
3: []
4: 0
5: ""
MAAT: ["Modulo de apoyo anatomía topográfica", "2", "CPP", ["MICB", "EU14", "BU6", "EU15"], 0, ""]
0: "Modulo de apoyo anatomía topográfica"
1: "2"
2: "CPP"
3: ["MICB", "EU14", "BU6", "EU15"]
0: "MICB"
1: "EU14"
2: "BU6"
3: "EU15"
4: 0
5: ""
MABL: ["Módulo de apoyo de bases legislativas", 2, "Custom", [], 0, ""]
0: "Módulo de apoyo de bases legislativas"
1: 2
2: "Custom"
3: []
4: 0
5: ""
MACA: ["Modulo de apoyo conducta aplicada", "2", "CPP", [], 0, ""]
0: "Modulo de apoyo conducta aplicada"
1: "2"
2: "CPP"
3: []
4: 0
5: ""
MAEP: ["Modulo apoyo ecología de poblaciones", "2", "CB", [], 0, ""]
0: "Modulo apoyo ecología de poblaciones"
1: "2"
2: "CB"
3: []
4: 0
5: ""
MAIG: ["Modulo de apoyo manipulación de info. genética", "2", "CPP", [], 0, ""]
0: "Modulo de apoyo manipulación de info. genética"
1: "2"
2: "CPP"
3: []
4: 0
5: ""
MAPLAN: ["Modulo de apoyo planificación", "2", "CPP", [], 0, ""]
0: "Modulo de apoyo planificación"
1: "2"
2: "CPP"
3: []
4: 0
5: ""
MAT-021: ["Matemáticas I", 5, "Custom", [], 8, "A"]
MAT-022: ["Matemáticas II", 5, "Custom", ["MAT-021"], 7, "A"]
MAT-023: ["Matemáticas III", 4, "Custom", ["MAT-022"], 7, "A"]
MAT-024: ["Matemáticas IV", 4, "Custom", ["MAT-023"], 6, "A"]
MICB: ["Modulo integrador ciclo basico", "5", "CB", [], 0, ""]
0: "Modulo integrador ciclo basico"
1: "5"
2: "CB"
3: []
4: 0
5: ""
MICP: ["Modulo integrador ciclo pro-profesional", "5", "CPP", [], 0, ""]
0: "Modulo integrador ciclo pro-profesional"
1: "5"
2: "CPP"
3: []
4: 0
5: ""
MMI001: ["Introduccion al manejo de la informacion", "2", "CB", [], 0, ""]
0: "Introduccion al manejo de la informacion"
1: "2"
2: "CB"
3: []
4: 0
5: ""
MU38: ["Medicina interna nivel I", "16", "CP", [], 0, "A"]
0: "Medicina interna nivel I"
1: "16"
2: "CP"
3: []
4: 0
5: "A"
MU39: ["Medicina interna nivel II", "5", "CP", ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"], 0, ""]
0: "Medicina interna nivel II"
1: "5"
2: "CP"
3: ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"]
4: 0
5: ""
MU40: ["Anestesiologia y cirugia Basica nivel I", "5", "CP",…]
0: "Anestesiologia y cirugia Basica nivel I"
1: "5"
2: "CP"
3: ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"]
4: 0
5: ""
MU41: ["Anestesiología y cirugía nivel II", "2", "CP", ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"], 0,…]
0: "Anestesiología y cirugía nivel II"
1: "2"
2: "CP"
3: ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"]
4: 0
5: ""
NU42: ["Patología en explotaciones masivas", "5", "CP", ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"], 0,…]
0: "Patología en explotaciones masivas"
1: "5"
2: "CP"
3: ["MICP", "MACA", "HU22", "UI29", "UI28", "HU23"]
4: 0
5: ""
OMV001: ["Orientacion a la medicina veterinaria", "3", "CB", [], 0, ""]
0: "Orientacion a la medicina veterinaria"
1: "3"
2: "CB"
3: []
4: 0
5: ""
P-PREPROF: ["Practica Pre-Profesional", "4", "CPP", [], 0, ""]
0: "Practica Pre-Profesional"
1: "4"
2: "CPP"
3: []
4: 0
5: ""
PBCB: ["Practica general basica", "2", "CB", [], 0, ""]
0: "Practica general basica"
1: "2"
2: "CB"
3: []
4: 0
5: ""
PBCL: ["Practica Clinica Basica", "4", "CB", [], 0, ""]
0: "Practica Clinica Basica"
1: "4"
2: "CB"
3: []
4: 0
5: ""
PBCP: ["Practica de campo basica", "4", "CB", [], 0, ""]
0: "Practica de campo basica"
1: "4"
2: "CB"
3: []
4: 0
5: ""
PPROF: ["Practica Profesional", "12", "CP", [], 0, ""]
0: "Practica Profesional"
1: "12"
2: "CP"
3: []
4: 0
5: ""
QUI-010: ["Química y Sociedad", 3, "Custom", [], 5, "A"]
SEM-A: ["Seminario espacio A", "3", "CB", [], 0, ""]
0: "Seminario espacio A"
1: "3"
2: "CB"
3: []
4: 0
5: ""
TALLERTI: ["Taller de actividades de titulacion", 2, "Custom", [], 0, ""]
0: "Taller de actividades de titulacion"
1: 2
2: "Custom"
3: []
4: 0
5: ""
UI26: ["Nutricion", "7", "CPP", [], 0, ""]
0: "Nutricion"
1: "7"
2: "CPP"
3: []
4: 0
5: ""
UI28: ["Reproduccion", "9", "CPP", [], 0, ""]
0: "Reproduccion"
1: "9"
2: "CPP"
3: []
4: 0
5: ""
UI29: ["Biotecnologia Reproductiva", "4", "CPP", [], 0, ""]
0: "Biotecnologia Reproductiva"
1: "4"
2: "CPP"
3: []
4: 0
5: ""





{1: ["AU1", "CU7", "MMI001", "OMV001", "INGB", "DU10"],…}
1: ["AU1", "CU7", "MMI001", "OMV001", "INGB", "DU10"]
0: "AU1"
1: "CU7"
2: "MMI001"
3: "OMV001"
4: "INGB"
5: "DU10"
2: ["AU3", "AU2", "CU8", "DU11", "BU4", "BU5", "SEM-A", "PBCB", "INGB", "E"]
0: "AU3"
1: "AU2"
2: "CU8"
3: "DU11"
4: "BU4"
5: "BU5"
6: "SEM-A"
7: "PBCB"
8: "INGB"
9: "E"
3: ["BU4", "BU4", "BU4", "EU13", "GU18-19", "CU9", "DU12", "PBCL", "INGP"]
0: "BU4"
1: "BU4"
2: "BU4"
3: "EU13"
4: "GU18-19"
5: "CU9"
6: "DU12"
7: "PBCL"
8: "INGP"
4: ["EU14", "GU18-19", "IU24", "EU15", "BU6", "FU16", "MAEP", "MICB", "INGP", "PBCP", "GU18-19", "INGP"]
0: "EU14"
1: "GU18-19"
2: "IU24"
3: "EU15"
4: "BU6"
5: "FU16"
6: "MAEP"
7: "MICB"
8: "INGP"
9: "PBCP"
10: "GU18-19"
11: "INGP"
5: ["HU20", "UI26", "JU30", "FU17", "MAIG", "P-PREPROF", "ELEC"]
0: "HU20"
1: "UI26"
2: "JU30"
3: "FU17"
4: "MAIG"
5: "P-PREPROF"
6: "ELEC"
6: ["HU21", "IU27", "IU25", "JU31", "E", "E", "MAAT", "Elec"]
0: "HU21"
1: "IU27"
2: "IU25"
3: "JU31"
4: "E"
5: "E"
6: "MAAT"
7: "Elec"
7: ["HU23", "MU38", "UI28", "UI29", "HU22", "KU32", "MACA", ""]
0: "HU23"
1: "MU38"
2: "UI28"
3: "UI29"
4: "HU22"
5: "KU32"
6: "MACA"
7: ""
8: ["KU33", "LU43", "KU34", "PPROF", "MAPLAN", "MICP", "", "LU36_I"]
0: "KU33"
1: "LU43"
2: "KU34"
3: "PPROF"
4: "MAPLAN"
5: "MICP"
6: ""
7: "LU36_I"
9: ["LU35_II", "LU37", "NU42", "MU40", "MU39", "KU35", "TALLERTI", "MABL"]
0: "LU35_II"
1: "LU37"
2: "NU42"
3: "MU40"
4: "MU39"
5: "KU35"
6: "TALLERTI"
7: "MABL"
10: [""]
0: ""

**Comment by maripidays** [comment]
hola! estuve revisando y cache que habian algunos sin categoria y ahora funciono!!! gracias jeje, cualquier novedad te aviso xddd

**Comment by maripidays** [comment]
mande el formulario :D

**Comment by BooterMan98** [comment]
Como te comente en la discusión, no voy a aceptar mallas de otras Ues, respecto a una forma de compartirla, estoy viendo como/que puedo hacer al respecto
