### ISSUE TITLE
Quiero agregar una Malla

### ISSUE THREAD

**Issue by uwo-o** [BooterMan98/malla-interactiva#38]
**Lic. en Quimica*

**Abreviatura de la carrera**
QUI

**Información de la malla**
Los siguientes datos fueron proporcionados por mi amiga Estefania (Fanny) Viveros, estudiante de ultimo año de Lic. en Quimica.
[Datos malla](https://drive.google.com/file/d/1oDSJ8cKqiqcTPh_bkNa3uEB16tzfiefZ/view?usp=sharing)

**Comment by uwo-o** [comment]
Quiero agregar esta malla

**Comment by BooterMan98** [comment]
para crear la malla, sigue el formato de archivos `data_CARR.json` y `colors_CARR.json` (https://github.com/BooterMan98/malla-interactiva?tab=readme-ov-file#Agregar-o-cambiar-una-malla) y guardalos `/data`.

luego edita el archivo `/data/carreras.json` para agregar la carrera y que se pueda ver en el selector

**Comment by uwo-o** [comment]
Agregue la info de respaldo

**Comment by BooterMan98** [comment]
Hola, acabo de hacer un merge de las mallas que actualizaste y agregaste. Te agradezco por tu aporte y al mismo tiempo me disculpo por la tardanza. Los cambios deberían de verse reflejados pronto en https://booterman98.github.io/malla-interactiva/ y en el mejor de los casos en https://mallas.labcomp.cl :D
